version: "3.5"

services:
  servera:
    container_name: servera
    build: ./server/
    ports:
      - "1443:443"
    networks:
      - OnePortalNetwork

  clienta:
    container_name: clienta
    build: ./client/
    ports:
      - "2443:443"
    networks:
      - OnePortalNetwork

networks:
  OnePortalNetwork:
    driver: bridge